name: OWASP ZAP DAST Scan (No Docker)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download and extract OWASP ZAP
        run: |
          env:
           ZAP_VERSION: "2.15.0"
           ...
          run: |
            wget https://github.com/zaproxy/zaproxy/releases/download/v${ZAP_VERSION}/ZAP_${ZAP_VERSION}_Linux.tar.gz
            tar -xzf ZAP_${ZAP_VERSION}_Linux.tar.gz
            mv ZAP_${ZAP_VERSION} zap_home

      - name: Run Passive Scan (Baseline)
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: |
          ./zap_home/zap.sh -cmd \
            -addonupdate \
            -quickurl $TARGET_URL \
          -quickout baseline-report.html \
            -quickprogress \
            -configfile zap/zap-baseline.conf

      - name: Run Active Scan (Full)
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: |
          ./zap_home/zap.sh -cmd \
            -addonupdate \
            -quickurl $TARGET_URL \
            -quickout fullscan-report.html \
            -quickprogress \
            -quickscan \
            -configfile zap/zap-fullscan.conf

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            baseline-report.html
            fullscan-report.html
